### PR TITLE
Adding a function in Functions_3D to read galprop-like templates

### PR DESCRIPTION
**Pull request by hayalaso**
I finalized the checks for the GalPropTemplate function. The function reads a file that has flux maps for different energy bins. The function was tested both with a Galprop model and a DRAGON model. Doing a fit where just the normalization is fitted, results for a pion decay model gave 6.4±0.38 for DRAGON and 7.0±0.98 for Galprop. 

I also added a 'fix' in _astromodels/core/model.py_ line 277, where a TypeError exception was added in order to add more parameters to the dictionary for cloning a model object, which might be useful for other functions. I put this change based on the suggestion and help from @henrikef.

### CODE REVIEW

**Comment by hayalaso** [comment]
Hi, just wanted to know if there are any updates on this request. Thanks.

**Comment by grburgess** [comment]
Hi, sorry for the delay! As this seems like simply a model addition, all is well. However, it would be useful to have a working example/ notebook doc on how to use the model either in the 3ML docs or here in astromodels. When we add new models to the 3ML/astromodels family that are intended for everyone, it is very useful that the community is able to use them easily and the best way to do this si via examples and/or documentation. Thank you!

**Comment by hayalaso** [comment]
I have an example on how to use it and I could add it. However, I was wondering about the galprop/dragon file I have. Do I also have to add that file to the repository?

**Comment by grburgess** [comment]
Hi. There are two options, you could add these to the data directory with some thought as to how they are imported, or put a description in the model as to where one would get the files. The first option is better. If you need help with this, let me know!

**Comment by hayalaso** [comment]
Sounds good. I'll try to get this as soon as possible.

**Comment by hayalaso** [comment]
Hi there, I finally got around this and made a short example on how to use the function. I added it to the examples folder. I also uploaded a model map that has Inverse Compton information, tho I modified a little bit since I wasn't sure I could post it here, even though the model is kinda old by now. Let me know if it looks good.

**Pull request merged**
