### PR TITLE
Py2to3

### PR DESCRIPTION
**Pull request by grburgess**
This is a branch up tp date with the fix_builds_nico branch that is also py3 compatible

### CODE REVIEW

**Comment by omodei** [comment]
Niccolo' found a conflict between the current version astromodels and this branch of threeml. It is due to noblas library. We see if we can fix it before merging.

**Comment by grburgess** [comment]
Can you specify what you mean? This is astromodels.

**Comment by ndilalla** [comment]
Since `python3` requires `readline >= 7` we probably need to release another version of `xspec-modelsonly` package, compiled with a different set of dependencies. I am starting to work on it.

**Comment by grburgess** [comment]
@ndilalla aha. Ok. Locally I see that it works for python3, but I'm not using conda. I've also go 3ML mostly working with python3, but I will not start testing until we get a build here as it is a dependency

**Comment by grburgess** [comment]
@ndilalla great work dude! I'll merge if you approve

**Comment by grburgess** [comment]
and @omodei :)

**Comment by ndilalla** [comment]
> @ndilalla great work dude! I'll merge if you approve

Thanks! :)

**Pull request merged**
