### PR TITLE
Adding the Galprop template to master astromodels

### PR DESCRIPTION
**Pull request by hayalaso**
Hi Giacomo, I got a few people asking about the 3D function to add diffuse emission templates. I was wondering if the function could be added. Since probably my fork is out of date, I figure sending you a copy of the function should be fine. I made a gist with just the function. 

Here is the link: https://gist.github.com/hayalaso/28b5d674c475e21fc2c71ad7a2c34260

As far as the tests Paco and I have done, it seems to work. I haven't had more chances to look at it since the collaboration meeting. I figure more eyes looking at it can find more problems. 

Best,
Hugo

### CODE REVIEW

**Comment by giacomov** [comment]
Hi @hayalaso , thanks for this!

Do you have an example of a FITS file I could use for testing?

**Comment by hayalaso** [comment]
I have updated the function for the GalProp 3D model in functions_3D.py. Thanks to @cbrisboi, the code runs much faster now. I would like to see if this can be pushed to the official _astromodels_ so that other people working on diffuse emission can use it. Simple calculations such as TS or likelihood values can be obtained with HAL. A problem, mentioned by @henrikef, is that HAL makes clones of the objects in _astromodels_ and it doesn't copy all the arguments of the object. So getting the TS of specific sources will give an error.

**Comment by hayalaso** [comment]
For a test module, would it be useful to add one of the templates I use in the data directory? It's 35M tho, kinda heavy. @grburgess @henrikef

**Comment by hayalaso** [comment]
I'll close the pull request for now. I keep finding some things to check. I'll reopen once the code is more robust

**Pull request closed without merging**
